#ifndef SONGMANAGER_H
#define SONGMANAGER_H

#include <map>
#include <set>
#include <unordered_map>

#include "Group.h"
class LoadingWindow;
class Song;
class Style;
class Steps;
class PlayerOptions;
struct lua_State;

#include <cstddef>
#include <string>
#include <unordered_set>
#include <vector>

#include "Course.h"
#include "Difficulty.h"
#include "GameConstantsAndTypes.h"
#include "PlayerOptions.h"
#include "RageTexturePreloader.h"
#include "RageTypes.h"
#include "RageUtil.h"
#include "Song.h"
#include "ThemeMetric.h"

std::string SONG_GROUP_COLOR_NAME(size_t i);
std::string COURSE_GROUP_COLOR_NAME(size_t i);
bool CompareNotesPointersForExtra(const Steps* n1, const Steps* n2);

/** @brief The max number of edit steps a profile can have. */
const int MAX_EDIT_STEPS_PER_PROFILE = 200;
/** @brief The max number of edit courses a profile can have. */
const int MAX_EDIT_COURSES_PER_PROFILE = 20;

/** @brief The holder for the Songs and its Steps. */
class SongManager {
 public:
  SongManager();
  ~SongManager();

  /**
   * @brief Initialize all songs from disk
   * @param ld the loading window to be updated, or nullptr
   * @param onlyAdditions only load songs added after the last
   *        invocation of this function
   */
  void InitSongsFromDisk(LoadingWindow* ld, bool onlyAdditions);
  void FreeSongs();
  void UnlistSong(Song* song);
  void Cleanup();

  void Invalidate(const Song* pStaleSong);

  void RegenerateNonFixedCourses();
  void SetPreferences();
  void SaveEnabledSongsToPref();
  void LoadEnabledSongsFromPref();

  void LoadStepEditsFromProfileDir(
      const std::string& sProfileDir, ProfileSlot slot);
  void LoadCourseEditsFromProfileDir(
      const std::string& sProfileDir, ProfileSlot slot);
  int GetNumStepsLoadedFromProfile();
  void FreeAllLoadedFromProfile(ProfileSlot slot = ProfileSlot_Invalid);

  void LoadGroupSymLinks(std::string sDir, std::string sGroupFolder);

  /**
   * @brief Initialize all courses from disk
   * @param ld the loading window to be updated, or nullptr
   * @param onlyAdditions only load courses added after the last
   *        invocation of this function
   */
  void InitCoursesFromDisk(LoadingWindow* ld, bool onlyAdditions);
  void InitAutogenCourses();
  void InitRandomAttacks();
  void FreeCourses();
  void AddCourse(Course* pCourse);     // transfers ownership of pCourse
  void DeleteCourse(Course* pCourse);  // transfers ownership of pCourse
  /** @brief Remove all of the auto generated courses. */
  void DeleteAutogenCourses();
  void InvalidateCachedTrails();

  /**
   * @brief Initialize all songs and courses from disk, and update
   *        autogenerated courses afterwards
   * @param ld the loading window to be updated, or nullptr
   * @param onlyAdditions only load songs and courses added after the
   *        last invocation of this function
   */
  void InitAll(LoadingWindow* ld, bool onlyAdditions);
  void Reload(bool bAllowFastLoad, LoadingWindow* ld = nullptr);
  void LoadAdditions(LoadingWindow* ld = nullptr);
  void PreloadSongImages();

  bool IsGroupNeverCached(const std::string& group) const;

  std::string GetSongGroupBannerPath(std::string sSongGroup) const;
  std::string GetSeriesBannerPath(std::string sSeriesName) const;
  // std::string GetSongGroupBackgroundPath( std::string sSongGroup ) const;
  void GetSongGroupNames(std::vector<std::string>& AddTo) const;
  bool DoesSongGroupExist(std::string sSongGroup) const;
  bool HasPackIni(const std::string& sSongGroup) const;
  RageColor GetSongGroupColor(const std::string& sSongGroupName) const;
  RageColor GetSongColor(const Song* pSong) const;

  std::string GetCourseGroupBannerPath(const std::string& sCourseGroup) const;
  // std::string GetCourseGroupBackgroundPath( const std::string &sCourseGroup )
  // const;
  void GetCourseGroupNames(std::vector<std::string>& AddTo) const;
  bool DoesCourseGroupExist(const std::string& sCourseGroup) const;
  RageColor GetCourseGroupColor(const std::string& sCourseGroupName) const;
  RageColor GetCourseColor(const Course* pCourse) const;

  void ResetGroupColors();

  static std::string ShortenGroupName(std::string sLongGroupName);
  static std::string ShortenSeriesName(std::string sLongSeriesName);

  // Lookup
  /**
   * @brief Retrieve all of the songs that belong to a particular group.
   * @param sGroupName the name of the group.
   * @return the songs that belong in the group. */
  const std::vector<Song*>& GetSongs(const std::string& sGroupName) const;
  /**
   * @brief Retrieve all of the songs in the game.
   * @return all of the songs. */
  const std::vector<Song*>& GetAllSongs() const { return GetSongs(GROUP_ALL); }
  /**
   * @brief Retrieve all of the popular songs.
   *
   * Popularity is determined specifically by the number of times
   * a song is chosen.
   * @return all of the popular songs. */
  const std::vector<Song*>& GetPopularSongs() const { return m_pPopularSongs; }

  /**
   * @brief Retrieve all of the songs in a group that have at least one
   * valid step for the current gametype.
   * @param sGroupName the name of the group.
   * @return the songs within the group that have at least one valid Step. */
  const std::vector<Song*>& GetSongsOfCurrentGame(
      const std::string& sGroupName) const;
  /**
   * @brief Retrieve all of the songs in the game that have at least one
   * valid step for the current gametype.
   * @return the songs within the game that have at least one valid Step. */
  const std::vector<Song*>& GetAllSongsOfCurrentGame() const;

  std::map<int, std::vector<Song*>> GetMeterToSongsMap() const {
    return m_mapSongsByDifficulty;
  }
  void GetPreferredSortSongs(std::vector<Song*>& AddTo) const;
  std::map<std::string, std::vector<Song*>> GetPreferredSortSongsMap() const {
    return m_mapPreferredSectionToSongs;
  };
  std::string SongToPreferredSortSectionName(const Song* pSong) const;
  std::unordered_map<std::string, Group*> GetGroupGroupMap() const {
    return m_mapNameToGroup;
  };
  struct Series {
    std::string sName;
    std::unordered_set<Group*> groups;
    std::string sBannerPath;
  };
  std::map<std::string, Series> GetSeriesGroupMap() const {
    return m_mapNameToSeries;
  };
  Group* GetGroupFromName(const std::string& sGroupName) const;
  Group* GetGroup(const Song* pSong) const;
  std::vector<std::string> GetPreferredSortSectionNames() const;
  std::vector<Song*> GetPreferredSortSongsBySectionName(
      const std::string& sSectionName) const;
  void GetPreferredSortSongsBySectionName(
      const std::string& sSectionName, std::vector<Song*>& AddTo) const;
  std::vector<Song*> GetSongsByMeter(int iMeter) const;
  const std::vector<Course*>& GetPopularCourses(CourseType ct) const {
    return m_pPopularCourses[ct];
  }
  Song* FindSong(std::string sPath) const;
  Song* FindSong(std::string sGroup, std::string sSong) const;
  Course* FindCourse(std::string sPath) const;
  Course* FindCourse(std::string sGroup, std::string sName) const;
  /**
   * @brief Retrieve the number of songs in the game.
   * @return the number of songs. */
  int GetNumSongs() const;
  int GetNumLockedSongs() const;
  int GetNumUnlockedSongs() const;
  int GetNumSelectableAndUnlockedSongs() const;
  int GetNumSongGroups() const;
  /**
   * @brief Retrieve the number of courses in the game.
   * @return the number of courses. */
  int GetNumCourses() const;
  int GetNumCourseGroups() const;
  Song* GetRandomSong();
  Course* GetRandomCourse();
  // sm-ssc addition:
  std::string GetSongGroupByIndex(unsigned index) {
    return m_sSongGroupNames[index];
  }
  int GetSongRank(Song* pSong);

  void GetStepsLoadedFromProfile(
      std::vector<Steps*>& AddTo, ProfileSlot slot) const;
  void DeleteSteps(Steps* pSteps);  // transfers ownership of pSteps

  void GetAllCourses(std::vector<Course*>& AddTo, bool bIncludeAutogen) const;
  void GetCourses(
      CourseType ct, std::vector<Course*>& AddTo, bool bIncludeAutogen) const;
  void GetCoursesInGroup(
      std::vector<Course*>& AddTo, const std::string& sCourseGroup,
      bool bIncludeAutogen) const;
  void GetPreferredSortCourses(
      CourseType ct, std::vector<Course*>& AddTo, bool bIncludeAutogen) const;

  void GetExtraStageInfo(
      bool bExtra2, const Style* s, Song*& pSongOut, Steps*& pStepsOut);
  Song* GetSongFromDir(std::string sDir) const;
  Course* GetCourseFromPath(
      std::string sPath) const;  // path to .crs file, or path to song group dir
  Course* GetCourseFromName(std::string sName) const;

  void UpdatePopular();
  void UpdateShuffled();  // re-shuffle songs and courses
  std::map<int, std::vector<Song*>> UpdateMeterSort(std::vector<Song*> songs);
  void SetPreferredSongs(std::string sPreferredSongs, bool bIsAbsolute = false);
  void SetPreferredSongsFromTable(
      std::map<std::string, std::vector<Song*>> mapSectionToSongs);
  void SetPreferredCourses(
      std::string sPreferredCourses, bool bIsAbsolute = false);
  void UpdatePreferredSort(
      std::string sPreferredSongs = "PreferredSongs.txt",
      std::string sPreferredCourses = "PreferredCourses.txt");
  void SortSongs();  // sort m_pSongs by CompareSongPointersByTitle

  void UpdateRankingCourses();  // courses shown on the ranking screen
  void RefreshCourseGroupInfo();

  // Lua
  void PushSelf(lua_State* L);

 protected:
  /**
   * @brief Load all songs from a directory
   * @param sDir the directory to be loaded
   * @param ld the loading window to be updated, or nullptr
   * @param onlyAdditions only load songs added after the last
   *        invocation of this function
   */
  void LoadSongDir(std::string sDir, LoadingWindow* ld, bool onlyAdditions);
  bool GetExtraStageInfoFromCourse(
      bool bExtra2, std::string sPreferredGroup, Song*& pSongOut,
      Steps*& pStepsOut, StepsType stype);
  bool SanityCheckGroupDir(std::string sDir) const;
  void AddGroup(std::string sDir, std::string sGroupDirName, Group* group);
  int GetNumEditsLoadedFromProfile(ProfileSlot slot) const;

  void AddSongToList(Song* new_song);
  /** @brief All of the songs that can be played. */
  std::vector<Song*> m_pSongs;

  std::map<std::string, Song*> m_SongsByDir;
  std::set<std::string> m_GroupsToNeverCache;

  /** @brief Hold pointers to all the songs that have been deleted from disk but
   * must at least be kept temporarily alive for smooth audio transitions. */
  std::vector<Song*> m_pDeletedSongs;

  /** @brief The most popular songs ranked by number of plays. */
  std::vector<Song*> m_pPopularSongs;
  std::vector<Song*> m_pShuffledSongs;  // used by GetRandomSong

  /** @brief Meter numbers and the songs with Steps that are within.*/
  std::map<int, std::vector<Song*>> m_mapSongsByDifficulty;

  struct PreferredSortSection {
    std::string sName;
    std::vector<Song*> vpSongs;
  };
  /** @brief All preferred songs, keyed by section */
  std::map<std::string, std::vector<Song*>> m_mapPreferredSectionToSongs;
  std::vector<PreferredSortSection> m_vPreferredSongSort;
  std::vector<std::string> m_sSongGroupNames;
  std::vector<std::string>
      m_sSongGroupBannerPaths;  // each song group may have a banner associated
                                // with it
  // vector<std::string>		m_sSongGroupBackgroundPaths; // each
  // song group may have a background associated with it (very rarely)

  std::unordered_map<std::string, Group*>
      m_mapNameToGroup;  // maps a group's name on disk (folder) to a Group
                         // object
  // maps a series name to Series object
  std::map<std::string, Series> m_mapNameToSeries;

  struct Comp {
    bool operator()(const std::string& s, const std::string& t) const {
      return CompareRStringsAsc(s, t);
    }
  };
  typedef std::vector<Song*> SongPointerVector;
  std::map<std::string, SongPointerVector, Comp> m_mapSongGroupIndex;

  std::vector<Course*> m_pCourses;
  std::vector<Course*> m_pPopularCourses[NUM_CourseType];
  std::vector<Course*> m_pShuffledCourses;  // used by GetRandomCourse
  struct CourseGroupInfo {
    std::string m_sBannerPath;
    // std::string m_sBackgroundPath;
  };
  std::map<std::string, CourseGroupInfo> m_mapCourseGroupToInfo;
  typedef std::vector<Course*> CoursePointerVector;
  std::vector<CoursePointerVector> m_vPreferredCourseSort;

  RageTexturePreloader m_TexturePreload;

  ThemeMetric<int> NUM_SONG_GROUP_COLORS;
  ThemeMetric1D<RageColor> SONG_GROUP_COLOR;
  ThemeMetric<int> NUM_COURSE_GROUP_COLORS;
  ThemeMetric1D<RageColor> COURSE_GROUP_COLOR;
  ThemeMetric<int> num_profile_song_group_colors;
  ThemeMetric1D<RageColor> profile_song_group_colors;
};

extern SongManager*
    SONGMAN;  // global and accessible from anywhere in our program

#endif

/**
 * @file
 * @author Chris Danford, Glenn Maynard (c) 2001-2004
 * @section LICENSE
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, and/or sell copies of the Software, and to permit persons to
 * whom the Software is furnished to do so, provided that the above
 * copyright notice(s) and this permission notice appear in all copies of
 * the Software and that both the above copyright notice(s) and this
 * permission notice appear in supporting documentation.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS
 * INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT
 * OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
 * OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
 * OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THIS SOFTWARE.
 */
