on:
  push:
  pull_request:
    paths-ignore:
      - '**.md'

name: Continuous integration

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15, macos-15-intel, windows-2022]
        include:
          - os: ubuntu-24.04
            name: Ubuntu (x86_64)
          - os: ubuntu-24.04-arm
            name: Ubuntu (ARM)
          - os: macos-15
            name: macOS (M1)
          - os: macos-15-intel
            name: macOS (Intel)
          - os: windows-2022
            name: Windows
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install dependencies
        uses: ./.github/actions/setup-env
        with:
          os: ${{ matrix.os }}
          ccache: 'true'
      - name: Configure
        run: cmake -B build -DCMAKE_COMPILE_WARNING_AS_ERROR=ON -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache ${{ env.CMAKE_FLAGS }}
      - name: Build
        run: cmake --build build ${{ env.CMAKE_BUILD_FLAGS }}
