on:
  push:
    branches:
      - beta
      - release

name: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15, macos-15-intel, windows-2022]
        club_fantastic: [Off, On]
        include:
          - os: ubuntu-24.04
            name: Ubuntu (x86_64)
          - os: ubuntu-24.04-arm
            name: Ubuntu (ARM)
          - os: macos-15
            name: macOS (M1)
          - os: macos-15-intel
            name: macOS (Intel)
          - os: windows-2022
            name: Windows

    name: "${{ matrix.name }} - ClubFantastic: ${{ matrix.club_fantastic }}"

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        uses: ./.github/actions/setup-env
        with:
          os: ${{ matrix.os }}
          ccache: 'false'

      - name: Create nightly release
        if: github.ref_name == 'beta'
        run: >
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release 
          -DWITH_FULL_RELEASE=Off -DWITH_NIGHTLY_RELEASE=On 
          -DWITH_CLUB_FANTASTIC=${{ matrix.club_fantastic }}
          ${{ env.CMAKE_FLAGS }}

      - name: Create full release
        if: github.ref_name == 'release'
        run: >
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release 
          -DWITH_FULL_RELEASE=On -DWITH_NIGHTLY_RELEASE=Off 
          -DWITH_CLUB_FANTASTIC=${{ matrix.club_fantastic }}
          ${{ env.CMAKE_FLAGS }}

      - name: Create package
        run: |
          if [ "${{ matrix.os }}" = "windows-2022" ]; then
            cmake --build build --config Release --target package
          else
            cmake --build build --target package
          fi
        shell: bash

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: ITGmania-${{ github.sha }}-${{ matrix.os }}-ClubFantastic-${{ matrix.club_fantastic }}
          path: ${{ env.ARTIFACT_PATH }}
          archive: false

      - uses: actions/attest@v4
        with:
          subject-name: ITGmania-${{ github.sha }}-${{ matrix.os }}-ClubFantastic-${{ matrix.club_fantastic }}
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
