on:
  push:
    branches:
      - beta
      - release

name: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      UBUNTU_INSTALL: |
        sudo apt-get update && sudo apt-get install -y \
        libasound2-dev libgl-dev libglu1-mesa-dev libgtk-3-dev libjack-dev \
        libmad0-dev libpulse-dev libudev-dev libxinerama-dev libx11-dev \
        libxrandr-dev libxtst-dev nasm
      MAC_INSTALL: brew install nasm
      PACKAGE_CMD: cmake --build build --target package
      PACKAGE_CMD_WINDOWS: cmake --build build --config Release --target package
      RELEASE_NIGHTLY_FLAGS: '-DCMAKE_BUILD_TYPE=Release -DWITH_FULL_RELEASE=Off -DWITH_NIGHTLY_RELEASE=On -DWITH_CLUB_FANTASTIC=Off'
      RELEASE_FULL_FLAGS: '-DCMAKE_BUILD_TYPE=Release -DWITH_FULL_RELEASE=On -DWITH_NIGHTLY_RELEASE=Off -DWITH_CLUB_FANTASTIC=Off'
    permissions:
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15, macos-15-intel, windows-2022]
        include:
          - os: ubuntu-24.04
            name: Ubuntu (x86_64)
            install: $UBUNTU_INSTALL
            configure: cmake -B build -DWITH_FFMPEG_JOBS="$(nproc)"
            release-nightly: $RELEASE_NIGHTLY_FLAGS
            release-full: $RELEASE_FULL_FLAGS
            package: $PACKAGE_CMD
            path: build/ITGmania-*.tar.gz
          - os: ubuntu-24.04-arm
            name: Ubuntu (ARM)
            install: $UBUNTU_INSTALL
            configure: cmake -B build -DWITH_FFMPEG_JOBS="$(nproc)"
            release-nightly: $RELEASE_NIGHTLY_FLAGS
            release-full: $RELEASE_FULL_FLAGS
            package: $PACKAGE_CMD
            path: build/ITGmania-*.tar.gz
          - os: macos-15
            name: macOS (M1)
            install: $MAC_INSTALL
            configure: cmake -B build -DCMAKE_OSX_ARCHITECTURES=arm64 -DWITH_FFMPEG_JOBS="$(sysctl -n hw.logicalcpu)"
            release-nightly: $RELEASE_NIGHTLY_FLAGS -DCMAKE_OSX_ARCHITECTURES=arm64
            release-full: $RELEASE_FULL_FLAGS -DCMAKE_OSX_ARCHITECTURES=arm64
            package: $PACKAGE_CMD
            path: build/ITGmania-*.dmg
          - os: macos-15-intel
            name: macOS (Intel)
            install: $MAC_INSTALL
            configure: cmake -B build -DCMAKE_OSX_ARCHITECTURES=x86_64 -DWITH_FFMPEG_JOBS="$(sysctl -n hw.logicalcpu)"
            release-nightly: $RELEASE_NIGHTLY_FLAGS -DCMAKE_OSX_ARCHITECTURES=x86_64
            release-full: $RELEASE_FULL_FLAGS -DCMAKE_OSX_ARCHITECTURES=x86_64
            package: $PACKAGE_CMD
            path: build/ITGmania-*-NIGHTLY-git-*-macOS-Intel-no-songs.dmg
          - os: windows-2022
            name: Windows
            configure: cmake -B build -DWITH_FFMPEG_JOBS="$env:NUMBER_OF_PROCESSORS"
            release-nightly: $RELEASE_NIGHTLY_FLAGS
            release-full: $RELEASE_FULL_FLAGS
            package: $PACKAGE_CMD_WINDOWS
            path: build/ITGmania-*.exe
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Cache CMake build directory
        uses: actions/cache@v5
        with:
          path: |
            build/*
            !${{ matrix.path }}
          key: ${{ runner.os }}-${{ runner.arch }}-cmake-build-${{ github.ref_name }}-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-cmake-build-${{ github.ref_name }}-
      - name: Install dependencies
        if: matrix.os != 'windows-2022'
        run: ${{ matrix.install }}
      - name: Add msbuild to PATH
        if: matrix.os == 'windows-2022'
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Create nightly release
        if: github.ref_name == 'beta'
        run: cmake -B build ${{ matrix.release-nightly }}
      - name: Create full release
        if: github.ref_name == 'release'
        run: cmake -B build ${{ matrix.release-full }}
      - name: Create package
        id: package
        run: ${{ matrix.package }}
      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v6
        with:
          name: ITGmania-${{ github.sha }}-${{ matrix.name }}
          path: ${{ matrix.path }}
          compression-level: 0
      - uses: actions/attest-build-provenance@v3
        with:
          subject-name: ITGmania-${{ github.sha }}-${{ matrix.name }}
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
