on:
  push:
    paths:
      - '**.xml'
  pull_request:
    paths:
      - '**.xml'

name: XML Validation

jobs:
  validate-xml-docs:
    name: Validate Lua.xml, LuaDocumentation.xml
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
      - name: Validate Lua.xml
        run: xmllint --noout Docs/Luadoc/Lua.xml
      - name: Validate LuaDocumentation.xml
        run: xmllint --noout Docs/Luadoc/LuaDocumentation.xml
